### PR TITLE
Reorganize into a python module

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by dtgay** [comment]
Awesome, was just gonna ask you about this in channel! Thanks!

**Comment by ralphbean** [comment]
Sweet!  :)

Upload it to PyPI once you get it where you want it.  I'll be rolling out badges.threebean.org with its own theme in the coming month(s).  we can share deployment methods (I'll be using ansible with this stuff:  https://github.com/ralphbean/snackpack )

**Comment by dtgay** [comment]
Yeah, I'll probably `sdist upload` the first release on Monday.

**Comment by ralphbean** [comment]
Pumped!

**Comment by ralphbean** [comment]
Don't forget `--sign`…  :b

**Comment by dtgay** [comment]
Haha damn should have done that for the bugfix Predestinate release I just cut

**Pull request merged**
